{% set name = "preshed" %}
{% set version = "2.0.1" %}
{% set sha256sum = "dae01c74313965c487e0ec839e5f28d0c7df9bfd1d978aa5bada3f72ff20a9e5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py<35]
    - python
    - setuptools
    - cymem >=1.30,<1.32

  run:
    - python
    - cymem >=1.30,<1.32

test:
  requires:
    - pytest

about:
  home: https://github.com/explosion/preshed
  license: MIT
  license_file: LICENSE
  summary: Cython Hash Table for Pre-Hashed Keys
  description: |
    Simple but high performance Cython hash table mapping pre-randomized keys
    to void* values.

extra:
  recipe-maintainers:
    - rmax
