{% set name = "preshed" %}
{% set version = "3.0.9" %}
{% set sha256sum = "721863c5244ffcd2651ad0928951a2c7c77b102f4e11a251ad85d37ee7621660" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win32 or linux32]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0
    - cython
    - msinttypes  # [win and py<35]
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0

test:
  requires:
    - pytest
  imports:
    - {{ name }}
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/preshed
  license: MIT
  license_file: LICENSE
  summary: Cython Hash Table for Pre-Hashed Keys
  description: |
    Simple but high performance Cython hash table mapping pre-randomized keys
    to void* values.

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - ines
    - honnibal
    - adrianeboyd
