appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sMi2G1V3KVWn3MRrrnP3LRroF5zuUFry02SKiGOzZqwZk18/MsMn5NW9Lkyoxsf6nTuCwYXd0e5F7ab0WTjRXYIY0xuwTqJ1uFHY3GnSbaoJWBPUgiEIey83t6ERljKPs5KVGV/PH2nqAFFN6yQQgkmQaXvZtXE3t4a21e3H6Ri3zb+8M2ZUSwXDw35H1r0OmvKmmYXTm25zgT70v6gnnNF6VJCSEz0n/MqYQour7ndQMp6rpWYlMmgx1gW5pFF04ViY4Q+IWgEJTz89WY/wvjLhbsmOve5dAdj7cIZRUSh56+y/nrlg+m3+RawDzjmil5NhLHK/9FBMfpqpUkSBFlSTkGx0PDIS9tqccsmFhOBsG3Ct6Z60zbpQ+DwGnidnvzEELralBvImf8VLjrpeXncPdKWpJf7nztCHQfkqNI1Ur0bw4TmjBfOQTsk/w/Fh5ZYZAp4O8NHn1+u7AIi/ibeuMLJecWYeYWsph4jUNKrl8Obon18eDOd8rQmzkCgmgOPCxrAZmLiHiQx/RLYiZij6KUconsjwUo1RcJF0oopKTZXUROPhmABaJ0YzE3Vcin9JiBo1XNzRfBq8CAE01WzaRfz5T+eU93QCVwRjnpWTssAZBVj+/bBa46+QwnnnrGrFOQzxRfAg28JfpwJuFr5dO15xmQoHmy1HbYXPSZ4=}
